export enum AppointmentStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  INTERRUPTED = 'INTERRUPTED',
  DISPUTED = 'DISPUTED',
  SETTLED = 'SETTLED',
}

export enum AppointmentType {
  NEW_PROBLEM = 'NEW_PROBLEM',
  FOLLOW_UP = 'FOLLOW_UP',
}

export enum TerminationReason {
  // CANCELLED
  CUSTOMER_CANCELLED_EARLY = 'CUSTOMER_CANCELLED_EARLY',
  CUSTOMER_CANCELLED_LATE = 'CUSTOMER_CANCELLED_LATE',
  DOCTOR_CANCELLED = 'DOCTOR_CANCELLED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_TIMEOUT = 'PAYMENT_TIMEOUT',
  SYSTEM_CANCELLED = 'SYSTEM_CANCELLED',

  //  NO_SHOW
  CUSTOMER_NO_SHOW = 'CUSTOMER_NO_SHOW',
  DOCTOR_NO_SHOW = 'DOCTOR_NO_SHOW',

  //  INTERRUPTED (After 'IN_PROGRESS')
  CUSTOMER_ISSUE = 'CUSTOMER_ISSUE',
  DOCTOR_ISSUE = 'DOCTOR_ISSUE',
  PLATFORM_ISSUE = 'PLATFORM_ISSUE',
}
